/* eslint-disable */
/*! @firebase/auth v1.7.0 | MIT License */
import {
    getAuth as getAuth,
    connectAuthEmulator as connectAuthEmulator,
    signInAnonymously as signInAnonymously,
    signInWithCustomToken as signInWithCustomToken,
    onAuthStateChanged as onAuthStateChanged,
    Auth as Auth,
    AuthError as AuthError,
    AuthErrorCodes as AuthErrorCodes,
    BrowserPopupRedirectResolver as BrowserPopupRedirectResolver,
    _getCurrentUser as _getCurrentUser,
    indexedDBLocalPersistence as indexedDBLocalPersistence,
    inMemoryPersistence as inMemoryPersistence,
    initializeAuth as initializeAuth,
    isSignInWithEmailLink as isSignInWithEmailLink,
    _getInstance as _getInstance,
    onIdTokenChanged as onIdTokenChanged,
    PhoneAuthProvider as PhoneAuthProvider,
    PhoneMultiFactorGenerator as PhoneMultiFactorGenerator,
    reauthenticateWithCredential as reauthenticateWithCredential,
    reauthenticateWithPhoneNumber as reauthenticateWithPhoneNumber,
    RecaptchaVerifier as RecaptchaVerifier,
    revokeToken as revokeToken,
    setPersistence as setPersistence,
    signInWithCredential as signInWithCredential,
    signInWithEmailAndPassword as signInWithEmailAndPassword,
    signInWithEmailLink as signInWithEmailLink,
    signInWithPhoneNumber as signInWithPhoneNumber,
    signInWithPopup as signInWithPopup,
    signInWithRedirect as signInWithRedirect,
    signOut as signOut,
    TwitterAuthProvider as TwitterAuthProvider,
    updateCurrentUser as updateCurrentUser,
    updateEmail as updateEmail,
    updatePassword as updatePassword,
    updatePhoneNumber as updatePhoneNumber,
    updateProfile as updateProfile,
    verifyBeforeUpdateEmail as verifyBeforeUpdateEmail,
    verifyPhoneNumber as verifyPhoneNumber,
    ActionCodeInfo as ActionCodeInfo,
    applyActionCode as applyActionCode,
    checkActionCode as checkActionCode,
    confirmPasswordReset as confirmPasswordReset,
    confirmSignInWithEmailLink as confirmSignInWithEmailLink,
    createUserWithEmailAndPassword as createUserWithEmailAndPassword,
    EmailAuthProvider as EmailAuthProvider,
    FacebookAuthProvider as FacebookAuthProvider,
    GameCenterAuthProvider as GameCenterAuthProvider,
    GithubAuthProvider as GithubAuthProvider,
    GoogleAuthProvider as GoogleAuthProvider,
    linkWithCredential as linkWithCredential,
    linkWithEmailAndPassword as linkWithEmailAndPassword,
    linkWithPhoneNumber as linkWithPhoneNumber,
    linkWithPopup as linkWithPopup,
    linkWithRedirect as linkWithRedirect,
    MultiFactorResolver as MultiFactorResolver,
    OAuthProvider as OAuthProvider,
    OperationType as OperationType,
    ParsedV2 as ParsedV2,
    ParsedV2Code as ParsedV2Code,
    parseActionCode as parseActionCode,
    performActionCode as performActionCode,
    reload as reload,
    sendEmailVerification as sendEmailVerification,
    sendPasswordResetEmail as sendPasswordResetEmail,
    setPersistence as setPersistence,
    setRestoration as setRestoration,
    signInWithCustomToken as signInWithCustomToken,
    signInWithEmailLink as signInWithEmailLink,
    signInWithPopup as signInWithPopup,
    signInWithRedirect as signInWithRedirect,
    signInWithVerificationCode as signInWithVerificationCode,
    SAMLAuthProvider as SAMLAuthProvider,
    sendSignInLinkToEmail as sendSignInLinkToEmail,
    signInWithCredential as signInWithCredential,
    signInWithPhoneNumber as signInWithPhoneNumber,
    User as User,
    UserCredential as UserCredential,
    UserInfo as UserInfo,
    isEmailVerified as isEmailVerified
} from 'https://www.gstatic.com/firebasejs/10.9.0/firebase-auth.js';
export {
    getAuth,
    connectAuthEmulator,
    signInAnonymously,
    signInWithCustomToken,
    onAuthStateChanged,
    Auth,
    AuthError,
    AuthErrorCodes,
    BrowserPopupRedirectResolver,
    _getCurrentUser,
    indexedDBLocalPersistence,
    inMemoryPersistence,
    initializeAuth,
    isSignInWithEmailLink,
    _getInstance,
    onIdTokenChanged,
    PhoneAuthProvider,
    PhoneMultiFactorGenerator,
    reauthenticateWithCredential,
    reauthenticateWithPhoneNumber,
    RecaptchaVerifier,
    revokeToken,
    setPersistence,
    signInWithCredential,
    signInWithEmailAndPassword,
    signInWithEmailLink,
    signInWithPhoneNumber,
    signInWithPopup,
    signInWithRedirect,
    signOut,
    TwitterAuthProvider,
    updateCurrentUser,
    updateEmail,
    updatePassword,
    updatePhoneNumber,
    updateProfile,
    verifyBeforeUpdateEmail,
    verifyPhoneNumber,
    ActionCodeInfo,
    applyActionCode,
    checkActionCode,
    confirmPasswordReset,
    confirmSignInWithEmailLink,
    createUserWithEmailAndPassword,
    EmailAuthProvider,
    FacebookAuthProvider,
    GameCenterAuthProvider,
    GithubAuthProvider,
    GoogleAuthProvider,
    linkWithCredential,
    linkWithEmailAndPassword,
    linkWithPhoneNumber,
    linkWithPopup,
    linkWithRedirect,
    MultiFactorResolver,
    OAuthProvider,
    OperationType,
    ParsedV2,
    ParsedV2Code,
    parseActionCode,
    performActionCode,
    reload,
    sendEmailVerification,
    sendPasswordResetEmail,
    setRestoration,
    sendSignInLinkToEmail,
    User,
    UserCredential,
    UserInfo,
    isEmailVerified
};
