/* eslint-disable */
/*! @firebase/app v0.10.1 | MIT License */
import {
    _addComponent as _addComponent,
    _DEFAULT_ENTRY_NAME as _DEFAULT_ENTRY_NAME,
    _is              as _is,
    _registerComponent as _registerComponent,
    _removeComponent as _removeComponent,
    create : create,
    get     : get,
    getApp as getApp,
    getApps as getApps,
    _get                  as _get,
    _set   : _set,
    _log   : _log,
    _INTERNAL                  : _INTERNAL,
    deleteApp as deleteApp,
    initializeApp as initializeApp,
    onLog as onLog,
    _apps as _apps,
    _components as _components,
    _SDK_VERSION as _SDK_VERSION,
    _DEFAULT_APP_NAME as _DEFAULT_APP_NAME,
    FirebaseAppImpl as FirebaseAppImpl,
    FirebaseApp as FirebaseApp,
    SDK_VERSION as SDK_VERSION
} from 'https://www.gstatic.com/firebasejs/10.9.0/firebase-app.js';
export {
    _addComponent,
    _DEFAULT_ENTRY_NAME,
    _is,
    _registerComponent,
    _removeComponent,
    create,
    get,
    getApp,
    getApps,
    _get,
    _set,
    _log,
    _INTERNAL,
    deleteApp,
    initializeApp,
    onLog,
    _apps,
    _components,
    _SDK_VERSION,
    _DEFAULT_APP_NAME,
    FirebaseAppImpl,
    FirebaseApp,
    SDK_VERSION
};
